version: "3"

services: 

  django:
    image: sangah/djangoapp:${MANAGER_VERION}
    environment:
    - ALLOWED_HOSTS
    volumes: 
    - "web-static:/opt/djangoapp/static"
    - "./local_settings.py:/opt/djangoapp/mainapp/local_settings.py"
    restart: "unless-stopped"

  nginx:
    build: nginx
    #network_mode: "service:manager"
    ports:
    - "$APP_LISTEN_PORT:80"
    depends_on: 
    - manager
    volumes: 
    - "web-static:/var/www/static"
    restart: "unless-stopped"

volumes: 
  web-static: