version: "3"

services: 

  manager:
    build: app
    environment:
    - ALLOWED_HOSTS
    ports:
    - "$MANAGER_LISTEN_PORT:8091"
    volumes: 
    - "./local_settings.py:/opt/djangoapp/mainapp/local_settings.py"